#!/usr/bin/env python3
"""Generate double-clickable launchers for this checkout.

The launchers hold absolute paths to this directory's virtualenv, so they are
generated rather than committed: a path baked on one machine is wrong on every
other one. Re-run this after moving or cloning the project.

    python scripts/make_launchers.py

Produces, under launchers/:
    Jarvis.app        macOS - double-click, or drag to the Dock
    Jarvis.bat        Windows - double-click, or pin to the Start menu
    jarvis.desktop    Linux - copy to ~/.local/share/applications/
"""

from __future__ import annotations

import os
import platform
import stat
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "launchers"


def venv_python(root: Path) -> Path:
    """The interpreter a launcher should use, whatever platform made it."""
    windows = root / ".venv" / "Scripts" / "python.exe"
    posix = root / ".venv" / "bin" / "python"
    if windows.exists():
        return windows
    if posix.exists():
        return posix
    # No virtualenv here: fall back to whatever is running this script, which
    # is at least an interpreter that could import the project.
    return Path(sys.executable)


def make_macos_app(root: Path, python: Path) -> Path:
    app = OUT / "Jarvis.app"
    macos = app / "Contents" / "MacOS"
    macos.mkdir(parents=True, exist_ok=True)

    (app / "Contents" / "Info.plist").write_text(f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Jarvis</string>
  <key>CFBundleDisplayName</key><string>Jarvis</string>
  <key>CFBundleIdentifier</key><string>local.jarvis.app</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleExecutable</key><string>Jarvis</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <!-- macOS shows this string in the microphone permission prompt. Without it
       the process is killed the moment it opens an input stream. -->
  <key>NSMicrophoneUsageDescription</key>
  <string>Jarvis listens to your voice so it can answer you.</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>LSUIElement</key><true/>
</dict>
</plist>
""")

    launcher = macos / "Jarvis"
    launcher.write_text(f"""#!/bin/bash
# Generated by scripts/make_launchers.py - re-run it if you move the project.
cd "{root}" || exit 1
exec "{python}" run.py app
""")
    launcher.chmod(launcher.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP
                   | stat.S_IXOTH)
    return app


def make_windows_bat(root: Path, python: Path) -> Path:
    # A .bat run from Explorer starts in the user's home, not next to itself.
    bat = OUT / "Jarvis.bat"
    win_python = root / ".venv" / "Scripts" / "python.exe"
    with open(bat, "w", newline="") as f:
        f.write("@echo off\r\n"
                "REM Generated by scripts/make_launchers.py\r\n"
                f'cd /d "{root}"\r\n'
                f'start "" "{win_python}" run.py app\r\n')
    return bat


def make_linux_desktop(root: Path, python: Path) -> Path:
    desktop = OUT / "jarvis.desktop"
    desktop.write_text(f"""[Desktop Entry]
Type=Application
Name=Jarvis
Comment=Voice assistant
Exec={python} {root}/run.py app
Path={root}
Terminal=false
Categories=Utility;AudioVideo;
""")
    desktop.chmod(desktop.stat().st_mode | stat.S_IEXEC)
    return desktop


def main() -> int:
    OUT.mkdir(exist_ok=True)
    python = venv_python(ROOT)
    if not python.exists():
        print(f"No interpreter found at {python}", file=sys.stderr)
        return 1

    made = [make_macos_app(ROOT, python),
            make_windows_bat(ROOT, python),
            make_linux_desktop(ROOT, python)]

    print(f"Using {python}\n")
    for path in made:
        native = ((platform.system() == "Darwin" and path.suffix == ".app")
                  or (platform.system() == "Windows" and path.suffix == ".bat")
                  or (platform.system() == "Linux" and path.suffix == ".desktop"))
        print(f"  {path.relative_to(ROOT)}{'   <- yours' if native else ''}")

    if platform.system() == "Darwin":
        print("\nDouble-click launchers/Jarvis.app, or drag it to the Dock.")
        print("Gatekeeper may object the first time: right-click it and choose"
              " Open.")
    elif platform.system() == "Windows":
        print("\nDouble-click launchers\\Jarvis.bat, or pin it to Start.")
    else:
        print("\nCopy launchers/jarvis.desktop to "
              "~/.local/share/applications/ to get a menu entry.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
